### ISSUE TITLE
"lwgeom_to_geojson: geometry type not supported" Error

### ISSUE THREAD

**Issue by kitzilla** [Oslandia/building-server#1]
Hi,
I was attending your 3D workshop @FOSS4G Bonn.
Back home, I am trying to setup building-server and follow the course materials again. 

I have followed the instructions here with no errors;
https://github.com/Oslandia/workshop-3d-itowns/blob/master/0_Data/1_Buildings.md
with a CityGML downloaded from here, which I believe identical to one of the workshop materials
http://donnees.ville.montreal.qc.ca/dataset/maquette-numerique-plateau-mont-royal-batiments-lod2-avec-textures/resource/c3fd01f1-2d0c-4727-b45e-2a9e62caadcd

I have installed building-server from your repository, configured settings.py and run processDB.py to build the quadtree. All went nicely till this point. (query=getCities is working for my installation)

Now I tried to run the sample client downloaded from here
https://github.com/Oslandia/workshop-3d-itowns/tree/master/www
but my building-server has crashed with the following error

```
mod_wsgi (pid=26593): Exception occurred processing WSGI script '/data/projects/citygml_montreal/building-server/server.py'.
Traceback (most recent call last):
File "/data/projects/citygml_montreal/building-server/server.py", line 40, in application
cityTable, tile, -offset[0], -offset[1], -offset[2], attributesStr))
InternalError: lwgeom_to_geojson: 'PolyhedralSurface' geometry type not supported
```

The message says that PostGIS (2.1 for my case) does not support polyhedralsurface whilst your code is written on that assumption. I have checked the sourcecode of the latest PostGIS 2.2.2 but lwgeom_to_geojson and ST_AsGeoJSON seem not supporting polyhedralsurface as well. But strangely, your demo server is creating GeoJson for Polyhedralsurfaces.
http://3d.oslandia.com/building?query=getGeometry&city=montreal&format=GeoJSON&tile=0/1/0

I wonder why my building-server did not go well like yours. Is it the version of GDAL/OGR on which PostGIS is depending? I have already googled the web but could not sort this out...

Many thanks,
Go Sato

**Comment by Jeremy-Gaillard** [comment]
Hello,

We used a slightly different version of PostGIS for the workshop to support the polyhedral surfaces export. You can find the patched version here: https://github.com/Jeremy-Gaillard/postgis/tree/polyhedral

We submitted the patch to PostGIS, so hopefully it will be integrated in the next version.

If you want to keep your current installation, you will have to convert the polyhedral surfaces to multipolygons. The following code allows you to change the type to multipolygonZ by editing the WKB header:

``` sql
-- Create a new geometry column "geom2" containing MULTIPOLYGONZ geometries
UPDATE <table> set geom2 = ('0106' || substring(geom::text from 5))::geometry;
-- Remove the old geometry column and rename the new column "geom"
```

Regards,

Jérémy Gaillard

**Comment by kitzilla** [comment]
Hello,

Thank you so much for the tips. As my DB is in Amazon RDS, I converted the geoms to MultyPolygonZ and now I can see the buildings sourced from my building-server instance.

By the way, I think line 31 - 32 of processDB.py should be tweaked like this

``` python
  for i in range(0, int(math.ceil(1.0 * extentX / maxTileSize))):
    for j in range(0, int(math.ceil(1.0 * extentY / maxTileSize))):
```

Othewise it won't create the quadtiles when extentX is smaller than maxTileSize. (1.0\* ensures the division to be done in float instead of int). 

Regards,
Go
