### ISSUE TITLE
Documentation about expected formats

### ISSUE THREAD

**Issue by ghost** [Oslandia/building-server#2]
I'm looking to stand up a WFS server in front of a PostGIS database containing a global OSM database of polyhedral surfaces defining building models for use with iTowns(2). I'm working on my first global import now and am looking ahead to the next steps.

In https://github.com/iTowns/itowns2/issues/183#issuecomment-256162546 you can see my existing format. It is 3DCityDB compatible and vertices are stored in lat/long. Is 3DCityDB supported? From https://github.com/Oslandia/cesium-buildings/issues/4#issuecomment-117800288, it's my understanding that EPSG:4326 is specifically supported? That was my issue with using the GLTF export process from 3DCityDB.

**Comment by Jeremy-Gaillard** [comment]
Hi,

First of all, this server does not rely on WFS (It seems that the Readme is out of date). We use a custom protocol for now, and may switch to 3D Portrayal Service in the future. We support this protocol in a branch of iTowns: https://github.com/iTowns/itowns2/tree/3Dbuildings

There is no specific support for 3DCityDB. We expect the geometries of a building to be in single table.

What do you mean exactly by EPSG:4326 being specifically supported? Do you need the geometries to be transformed into world coordinates before being converted?

**Comment by ghost** [comment]
> There is no specific support for 3DCityDB. We expect the geometries of a building to be in single table.

Ok. Could you guide me on the column names, etc? I can easily change my DB schema to match anything that stores polyhedral surfaces.

> What do you mean exactly by EPSG:4326 being specifically supported? Do you need the geometries to be transformed into world coordinates before being converted?

I store the surfaces in lat/lon to avoid placement issues as you move towards the poles. Unfortunately I've found that the 3DCityDB export tool for GLTF doesn't do any sort of Relative To Center placement in latitude/long (RTC), so GLTF doesn't work.

**Comment by Jeremy-Gaillard** [comment]
Your geometry table must have a "gid" column and a "geom" column.

The geometries are sent with an offset corresponding to the south-west corner of the tile. So, for sufficiently small tiles, you should have sufficient precision. Change the "maxtilesize" property in the settings file to ensure this.

~~I would also recommend using the more polished version that is in the "indus_flask" branch, it has more precise instructions and a more reliable installation procedure.~~

Edit: we just merged the branch into the master

**Comment by ghost** [comment]
K, awesome. I've been rather busy lately getting the first import done, 
but I will be looking at this in the next day or two.
